name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 18,10 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: '检测代码'
        uses: actions/checkout@v2
      - name: '初始化Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.15'
      - name: '安装依赖包'
        run: python -m pip install --upgrade requests
      - name: '开始签到'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python main.py
